### PR TITLE
Fix support for some faulty implementations

### LINKED ISSUE #6: oauth_callback_confirmed for wrongly implemented backends
I have tried using this library in my flutter application, but I have found, that the API I am trying to access, has a faulty OAuth implementation.
When requesting the temporary credentials, it returns `oauth_callback_confirmed=1` instead of `oauth_callback_confirmed=true`.
As I have seen across the internet, many APIs are implemented in this way (which is not the RFC 5849 norm, I know).
Therefore, many users could have this problem right now (or in the future).
The issue in [this line](https://github.com/nbspou/dart-oauth1/blob/fork/nbspou/lib/src/authorization.dart#L56).
One could add another case to it, where it checks like this;
```
String confirmed = params['oauth_callback_confirmed'].toLowerCase();
if (confirmed != 'true' || confirmed != '1') {
```
But I don't know, if it is the right way to include support for faulty implementations in libraries like this one.

Is there maybe any way I could solve the issue myself here or does it really need changes in the library?

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Fixes #6

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
I just tested it on my local machine and this really fixes the linked issue.

**Comment by kaetemi** [comment]
Cool. Will apply it tomorrow.

**Comment by ThexXTURBOXx** [comment]
Thank you very much!

**Comment by ThexXTURBOXx** [comment]
I'm sorry to bother you again, but when will you merge and publish this approximately?
My projects depend on this "fix" and I want to be able to plan my further steps in those projects :)

**Comment by kaetemi** [comment]
Thanks for the reminder. Pushed to dart pub.

**Comment by ThexXTURBOXx** [comment]
Oh, that was fast. Thank you very much :)

**Pull request merged**
